### ISSUE TITLE
Zoom around cursor

### ISSUE THREAD

**Issue by whiterook6** [zcreativelabs/react-simple-maps#132] opened 2019-03-19 18:03 UTC
I can implement a nice zoom function like this:

```
public componentDidMount(){
    this.node = ReactDOM.findDOMNode(this.refs.ComposableMap);
    if (this.node){
        this.node.addEventListener('mousewheel', this.handleScroll);
    }
}

public componentWillUnmount() {
    if (this.node){
        this.node.removeEventListener('mousewheel', this.handleScroll);
    }
}

public handleScroll = (event: WheelEvent) => {
    const { deltaY } = event;
    const clampedDeltaY = clamp(-50, 50, deltaY);
    const newZoom = this.state.zoom * (1 + (clampedDeltaY / 100));
    const clampedNewZoom = clamp(1, 10, newZoom);

    this.setState({zoom: clampedNewZoom});
}
// ...
<ComposableMap ref="ComposableMap">
    <ZoomableGroup zoom={this.state.zoom}>
```
And if I'm really clever I can grab the position of the mouse from the mouse event and even invert it from the zoomable projection, though I'm not sure it takes into account the panning functionality of the zoomable group

But I would like to be able to update the center of the map based on where the cursor when the zoom happens. The zoom should center around the cursor when using a mouse, like in this example: https://bl.ocks.org/mbostock/2206340

Is there a way to update the center while respecting the panning from the map as well? If I hover my cursor above europe and scroll the wheel I don't want to zoom in off the coast of africa.

**Comment by AdriaanKuipers** [comment] 2019-03-20 10:41
I'm looking for the exact same thing.

You can keep track of the center like this

```js
handleMoveEnd(newCenter) {
  this.setState({
    center: newCenter
  });
}
```

And

```js
<ZoomableGroup
    onMoveEnd={this.handleMoveEnd}
>
```

**Comment by AdriaanKuipers** [comment] 2019-03-20 13:37
Still missing compensation for the zoom level: [demo](https://codesandbox.io/s/218wpw3okn)

based on [this](https://github.com/zcreativelabs/react-simple-maps/issues/34#issuecomment-400725614)

**Comment by AdriaanKuipers** [comment] 2019-03-20 14:29
Basic working example here: [demo](https://codesandbox.io/s/218wpw3okn)

based on [this](https://github.com/zcreativelabs/react-simple-maps/issues/34#issuecomment-400725614)

**Comment by AdriaanKuipers** [comment] 2019-03-20 22:04
I had something close to working as you describe it; _move center to cursor on zoom_. But it became very difficult to control as the map will jump the whole time. Most online maps seem to make sure the location underneath the cursor stays the same whilst zooming.

This might help you: [codesandbox](https://codesandbox.io/s/y0131j50jj)
I'm not quite there yet. I didn't find the exact formula yet to make sure the same location stays under the cursor, and zooming far away from the center gives weird results. But it's a step in the right direction, I think.

If anyone finds how to do this, please let me know.

**Comment by guilleva** [comment] 2019-05-03 23:59
@AdriaanKuipers did you manage to get working properly? I'm also trying to accomplish the same thing.

**Comment by AdriaanKuipers** [comment] 2019-05-04 21:12
@guilleva not really. [this codesandbox](https://codesandbox.io/s/218wpw3okn) is a bit smoother. I think the only difference is adding 1 to zoom/subtracting 1 from zoom when zooming, instead of multiplication/division. 

Zooming in and out on Europe works pretty well. But if you test Australia, you'll find that it's still bugged... First zoom in is fine, second will move you to Africa.
I think zoom needs to compensated for somewhere before *projection.invert*. But I haven't looked at this for over a month now, it's all a bit misty...

**Comment by guilleva** [comment] 2019-05-09 23:43
thanks @AdriaanKuipers I also tried something similar without any luck! :(

**Comment by AdriaanKuipers** [comment] 2019-05-11 22:05
@guilleva the problem is feeding `projection.invert` with values outside of the box. (below zero, or above width/height of Composeable map)

**Comment by zimrick** [comment] 2020-03-27 18:49
Closing this. Proper wheel and scroll zoom are now implemented and should be working in a robust way on both desktop and mobile with v2.

**Closed by zimrick** 2020-03-27 18:49 UTC
